# **CREACIÓN DEL ENTORNO (.venv)**   
Para que funcione correctamente:
1. Instalamos python la versión 3.13.12 (es la que he probado yo)

2. Creamos un entorno virtual (recomendado para no tener trescientos paquetes instalados)
    - Haciendo Crtl+Shift+P y seleccionando "Python: Create Environment".
    - Te tiene que haber creado una dirección en la carpeta .venv.
    - Podemos comprobarlo abriendo una terminal y ponemos "pip --version" y tiene que salir la dirección de la carpeta .venv.

# **BIBLIOTECAS NECESARIAS**

In [11]:
# Importamos las librerias necesarias
from googleapiclient.discovery import build
from yt_dlp import YoutubeDL
import pprint as pprint
import re
import glob
import os
import json

import numpy as np
import pandas as pd
from pandas import DataFrame

c:\Users\Marina\Documents\Uni\ProyectoDatos\c2526-R1\.venv\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.0.1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

# **GUARDAR API KEY Y CREAR EL "SERVIDOR"**
La función build nos construye un objeto de la API de Youtube, que usaremos para que llame a la API y acceder a los datos.

In [12]:
# Guardamos nuestra API_KEY leyendo de la carpeta privada
with open("../Private/Claves.json", "r", encoding="utf-8") as archivo:
    claves = json.load(archivo)
API_KEY = claves["Clave_API"]
if API_KEY:
    print("Loaded API_KEY succesfully")

Loaded API_KEY succesfully

In [5]:
# Construimos el objeto de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# **FUNCIÓN PARA LIMPIAR EL TEXTO**

In [6]:
#Función temporal para limpiar texto
import re

def clean_vtt(text):
    text = re.sub(r"WEBVTT.*\n", "", text)
    text = re.sub(r"\d+:\d+:\d+\.\d+ --> .*", "", text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"\n+", "\n", text)
    return text.strip()

def clean_vtt_smart(text):
    lines = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if not lines or not line in lines[-1]:
            lines.append(line)
    return " ".join(lines)

# **GENERAMOS UNA PEQUEÑA BASE DE DATOS**
Lo guardaremos en un archivo csv, guardando la información de 50 videos.

In [7]:
# Lista de los id de los videos (usando el id el coste de la consulta es el mmínimo)
list_id = [
    'y5qZyNjjd4A', '-EOCVYvDY14', 'xtvM1BeGhXQ', 'TK0ERlbF_jE', 'wQK47p3lsn8', 'v9M7g-nKMBU', '5FRA7UXlGu8', 'TEA-hKkWDKM', 'Z-tbr5L0XDE', 'fLJBzhcSWTk', 
    'mDbpbPHW8bg', 'um1-gqoCJNA', 'Lmu6z4aj3Vk', 'WXhZGtVvwUo', 'Yasyj-0pjRI', '9shK1SmrWsU', '6qhuPwTcc50', 'nBdMdTpyPqk', 'UiCJhSuLdok', 'APD3ESDsqL0', 
    'DAv10RDdr9U', 'Cdg9UbVD9yo', 'FT-C0zSKQH8', 'C9VC6kt1ors', 'vZnPo0fPqqY', 'UplwT_a1IT8', 'itl1Lf4hq7c', 'cAeDOt8kI4g', 'JF5x6qgdi-8', 'E4p3-IpaIzE', 
    '6izsSWPPYsc', 'eTJQFu9JK6A', '80c6rdulV8o', 'Jp24nGUPoR0', 'pq330xEyTuY', 'vfIupidHgQg', 'dAVJO18j-do', 'uKzjZu_KVzU', 'WgIpM-4ZX88', 'PrBUjXaRSUQ', 
    '-G0u13COALA', 'sxDHyYpQNBk', 'dRBowc83jVs', '4k_2sjvnasE', '3Wn69w0W9C8', '8KIYBNbbK4E', 'P4QAFljGP7s', '_G6NtIVZhRE', 'cPN4H0sSCHQ', 'YTbRsGRWZW0'
    ]

# Creo el dataframe vacío
df_data = pd.DataFrame({
    "ID": [],
    "Titulo": [],
    "Descripcion": [],
    "Visualizaciones": [],
    "Numero_likes": [],
    "Duracion": [],
    "Fecha_publicacion": [],
    "Titulo_canal": [],
    "Subtitulos": []
})
df_data

Empty DataFrame
Columns: [ID, Titulo, Descripcion, Visualizaciones, Numero_likes, Duracion, Fecha_publicacion, Titulo_canal, Subtitulos]
Index: []

In [8]:
from urllib import response


def get_info(id_video):
    """ Saca la información del video, si hay subtítulos los limpia, y añade dichos datos al dataframe. """
    
    # Inicializamos la variable de los subtitulos
    cleant_sub = None

    # Hacemos la llamada a la API para obtener los detalles del video
    request = youtube.videos().list(
        part="snippet,contentDetails,statistics,status,topicDetails,recordingDetails",
        id=id_video
    )  

    # Ejecutamos la solicitud
    response = request.execute()

    if not response["items"]:
        return None
    
    video = response["items"][0]

    has_captions = video["contentDetails"].get("caption") in ["true", True]

    # --- SUBTÍTULOS ---
    if (video["contentDetails"].get("caption") == "true"):
        url =  "https://www.youtube.com/watch?v=" + id_video
        # Opciones de descarga
        ydl_opts = {
            "skip_download": True,
            "writesubtitles": True,
            "writeautomaticsub": True,      # subtítulos automáticos
            "subtitleslangs": ["en"], # idioma
            "subtitlesformat": "vtt",       # formato
            "outtmpl": f"subs/{id_video}.%(ext)s",
            "quiet": True
        }

        with YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])

        vtt_file = f"subs/{id_video}.en.vtt"

        if os.path.exists(vtt_file):
            with open(vtt_file, "r", encoding="utf-8") as f:
                subtitles = f.read()

            clean_sub = clean_vtt(subtitles)
            cleant_sub = clean_vtt_smart(clean_sub)

            # Borramos el archivo de subtítulos descargado tras limpiarlo
            # os.remove(vtt_file)
    
    # --- GENEROS ---
    generos = video.get("topicDetails", {}).get("topicCategories", [])

    if generos:
        generos = [
            genre.split("/")[-1].replace("_", " ")
            for genre in generos
        ]
        generos_str = ", ".join(generos)
    
    else:
        generos_str = "None"

    # --- DATAFRAME ---
    df_video = pd.DataFrame({
        "ID": id_video,
        "Titulo": video["snippet"]["title"],
        "Descripcion": video["snippet"]["description"],
        "Visualizaciones": video["statistics"]["viewCount"],
        "Numero_likes": video["statistics"].get("likeCount", None),
        "Duracion": video["contentDetails"]["duration"],
        "Fecha_publicacion": video["snippet"]["publishedAt"],
        "Titulo_canal": video["snippet"]["channelTitle"],
        "Subtitulos": cleant_sub if has_captions and cleant_sub else "None",
        "Generos": generos_str
    }, index=[0])

    return df_video

In [9]:
df_videos = []

for id in list_id:
    df_videos.append(get_info(id))

df_data = pd.concat(df_videos, ignore_index=True)

WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
WARNING: The extractor specified to use impersonation for this download, but no impersonate target is available. If you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies

WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
WARNING: The extractor specified to use impersonation for this download, but no impersonate target is available. If you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies

WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
WARNING: The extractor specified to use impersonation for this download, but no impersonate target is available. If you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies

In [10]:
df_data

,ID,Titulo,Descripcion,Visualizaciones,Numero_likes,Duracion,Fecha_publicacion,Titulo_canal,Subtitulos,Generos
0,y5qZyNjjd4A,Orishas- El kilo (High Quality) Official Video,DISCLAIMER: music and video belongs to its res...,1816640,16525,PT3M45S,2011-02-15T11:01:25Z,philippekogler,None,"Hip hop music, Music, Music of Latin America, ..."
1,-EOCVYvDY14,How Jynxzi Saved Rocket League *JYNXZI REACTS*,How Jynxzi Saved Rocket League\n\nOriginal Cre...,757388,16441,PT29M11S,2026-02-03T00:19:05Z,Jynxzi Live,None,"Racing video game, Sports game, Video game cul..."
2,xtvM1BeGhXQ,Evento “Together for Democracy” de @democracyf...,,10459,1122,PT2M54S,2026-02-02T19:28:41Z,JmMonteBlack,None,"Politics, Society"
3,TK0ERlbF_jE,Guzo - Guzo - Kingdom Sound Live Production Al...,Guzo - Guzo - Kingdom Sound Live Production Al...,1439172,20394,PT13M4S,2025-08-16T04:30:16Z,Kingdom Sound,"Kind: captions Language: en Though He was God,...","Christian music, Music, Religion"
4,wQK47p3lsn8,How to become King of an existing Kingdom in M...,If founding your own kingdom sounds like too m...,1148180,26470,PT41S,2025-05-18T17:00:35Z,TaleWorlds Entertainment,None,"Action-adventure game, Action game, Role-playi..."
5,v9M7g-nKMBU,Holy Diver,Provided to YouTube by Rhino/Warner Records\n\...,24061620,288074,PT5M54S,2014-11-08T22:46:06Z,Dio - Topic,None,"Music, Rock music"
6,5FRA7UXlGu8,Heaven and Hell (2021 Remaster),Provided to YouTube by Rhino/Warner Records\n\...,3473767,40274,PT6M58S,2021-03-05T03:32:47Z,Black Sabbath - Topic,None,"Music, Rock music, Soul music"
7,TEA-hKkWDKM,"Decades of Anti-Immigration Policy Created ""Ma...",Support our work: https://democracynow.org/don...,137132,3191,PT14M6S,2026-01-28T15:54:32Z,Democracy Now!,None,"Politics, Society"
8,Z-tbr5L0XDE,Kilo,Provided to YouTube by Ditto Music\n\nKilo · Y...,844820,11593,PT4M8S,2018-06-07T21:42:02Z,Yung Bleu - Topic,None,"Hip hop music, Music"
9,fLJBzhcSWTk,Why Socrates Hated Democracy,We’re used to thinking hugely well of democrac...,14092867,589519,PT4M22S,2016-11-28T14:00:02Z,The School of Life,Kind: captions Language: en We are used to thi...,Knowledge
10,mDbpbPHW8bg,Watsebha - Kingdom (Official Audio),"Kingdom\n\nA theater marches on the field,\nTh...",881814,6038,PT2M51S,2025-02-24T12:54:53Z,Watsebha,None,"Electronic music, Hip hop music, Music"
11,um1-gqoCJNA,Bro fought the Kingdom's Best Warrior 💀🔥,,47554,2017,PT20S,2026-02-02T20:29:34Z,Sptar,None,"Entertainment, Film"
12,Lmu6z4aj3Vk,Kilo of gold on the beach in a day,Credit: @X-Finds,7911050,344924,PT41S,2024-12-17T00:00:13Z,Infinite Shorts,None,Entertainment
13,WXhZGtVvwUo,Kilo - Chemin de la victoire (Official music v...,Shot by Vlady Design \nEdited by AKR\n\nMix an...,905666,8261,PT2M56S,2022-09-12T10:00:17Z,Kilo Official,None,"Hip hop music, Music"
14,Yasyj-0pjRI,Kingdom,Provided to YouTube by DistroKid\n\nKingdom · ...,1266758,17845,PT3M16S,2018-10-12T04:26:05Z,Iniko - Topic,None,"Electronic music, Hip hop music, Independent m..."
15,9shK1SmrWsU,Caught in the Middle (2016 Remaster),Provided to YouTube by Rhino/Warner Records\n\...,782542,9089,PT4M18S,2016-07-23T01:25:18Z,Dio - Topic,None,"Music, Pop music, Rock music, Soul music"
16,6qhuPwTcc50,Asael González - Libros x Kilos (Video Oficial),"Video oficial de ""Libros x Kilos"" de Asael Gon...",4420816,39324,PT2M26S,2023-06-01T13:33:40Z,Asael González Official,None,"Music, Music of Latin America"
17,nBdMdTpyPqk,WHAT IS DEMOCRACY | Educational Videos for Chi...,The Greek polis represents the beginnings of d...,35853,109,PT4M57S,2024-02-20T10:02:16Z,Happy Learning English,None,Knowledge
18,UiCJhSuLdok,"So, What is Democracy Anyway? | Peter Emerson ...","In many instances, a majority vote identifies ...",89691,1623,PT13M48S,2017-12-04T16:42:14Z,TEDx Talks,Kind: captions Language: en Translator: Veroni...,"Politics, Society"
19,APD3ESDsqL0,Young Smokes - Kilos [Music Video] @Smokeslocc...,► SUBSCRIBE to our channel to get the latest v...,13703514,63287,PT2M47S,2017-04-11T16:00:01Z,Link Up TV,None,"Hip hop music, Music, Pop music"
20,DAv10RDdr9U,"Dad Reacts to Ariana Grande - thank u, next",new thumbnail who dis\n\nFULL EPISODE ON PATRE...,112659,6415,PT35M2S,2026-02-02T19:55:31Z,turning the tables,None,Music
21,Cdg9UbVD9yo,All Good Things - Kingdom (Official Music Video),The Retaliators Movie: Buy or rent everywhere ...,409848,8002,PT4M33S,2020-09-25T04:15:00Z,Better Noise Music,None,"Electronic music, Independent music, Music, Po..."
22,FT-C0zSKQH8,Tink f/ Lil Herb & Lil Bibby - Kilo (Official ...,Tink f/ Lil Herb & Lil Bibby - Kilo\nProduced ...,1263532,12529,PT5M15S,2013-07-23T19:12:03Z,A Zae Production,None,"Hip hop music, Music"
23,C9VC6kt1ors,REACTING TO MY DHAR MAN VIDEO!,subscribe for more :)\n\nFOLTYN FAMILY MERCH: ...,5009997,93902,PT33M18S,2025-12-06T04:36:08Z,Foltyn Reacts,None,"Entertainment, Film"
24,vZnPo0fPqqY,Brit Reacts to British Grandad tries American ...,"Please subscribe, like and turn on notificatio...",48063,5115,PT18M1S,2026-02-03T00:45:24Z,L3WG Reacts,None,"Food, Lifestyle (sociology)"
25,UplwT_a1IT8,DEMOCRACY: Ancient vs. Modern,"An explanation of democracy, by way of explain...",901529,22142,PT45M2S,2023-03-10T22:54:05Z,Ryan Chapman,None,Knowledge
26,cAeDOt8kI4g,Rainbow in the Dark (2022 Remaster),Provided to YouTube by Rhino/Warner Records\n\...,1822652,19010,PT4M15S,2022-07-08T04:08:56Z,Dio - Topic,None,"Music, Pop music, Rock music"
27,JF5x6qgdi-8,MINIMINTER REACTS TO DEJI TRYING INDIAN KFC,@Deji Original Video: https://www.youtube.com/...,289615,9885,PT15M49S,2026-02-02T15:00:36Z,MiniminterClips,None,"Food, Lifestyle (sociology)"
28,E4p3-IpaIzE,Florida Kilos,Provided to YouTube by Universal Music Group\n...,21428987,167295,PT4M17S,2018-11-03T07:05:27Z,Lana Del Rey - Topic,None,"Electronic music, Independent music, Music, Po..."
29,6izsSWPPYsc,"Adam Calhoun - ""Kingdom""",I'm going on TOUR! love y'all man. The War Tou...,163079,8278,PT2M59S,2025-09-03T16:06:33Z,Adam Calhoun,None,"Hip hop music, Music"
30,eTJQFu9JK6A,Try Not To Sing: Songs That Turn 20 In 2026! (...,These songs turn 20 in 2026! Which song is you...,325064,10250,PT22M29S,2025-12-30T20:00:36Z,REACT,None,Music
31,80c6rdulV8o,How Democratic Is the Democratic People’s Repu...,It’s a country that has the words “democratic”...,110017,2880,PT47M58S,2026-01-30T12:00:14Z,In the Kimdom,None,"Politics, Society"
32,Jp24nGUPoR0,"Top U.S. & World Headlines — January 27, 2026",Support our work: https://democracynow.org/don...,520164,9865,PT12M20S,2026-01-27T15:29:00Z,Democracy Now!,None,"Politics, Society"
33,pq330xEyTuY,Dio - All The Fools Sailed Away (Official Musi...,You're watching the official music video for D...,1914062,27736,PT4M28S,2019-07-13T15:00:04Z,RHINO,None,"Music, Pop music, Rock music, Soul music"
34,vfIupidHgQg,Cinna reacts to NMS Boxing 3,Watch Cinna Live ▼\nhttps://www.twitch.tv/cinn...,39780,1101,PT1H38M18S,2026-02-02T15:00:00Z,Cinna LIVE,None,Boxing
35,dAVJO18j-do,Dio - Man On The Silver Mountain Live In Londo...,Holy Diver DVD,4020288,36041,PT5M19S,2010-10-08T16:06:09Z,DIOCIRCLE,None,"Music, Rock music"
36,uKzjZu_KVzU,Kingdom | Trailer – BBC,Some will rise... Others will fall. Who will r...,171922,4082,PT1M3S,2025-10-23T14:01:28Z,BBC,None,"Entertainment, Film"
37,WgIpM-4ZX88,CDobleta x YovngChimi - K.D.P. (Official Video),CDobleta x Yovng Chimi - K.D.P. (Official Vide...,35769343,264284,PT4M2S,2023-10-06T05:00:10Z,CDOBLETA,None,"Hip hop music, Music"
38,PrBUjXaRSUQ,Dio - Rainbow In The Dark (Official Music Vide...,You're watching the official music video remas...,31484602,247579,PT4M12S,2019-07-10T15:04:59Z,RHINO,None,"Music, Pop music, Rock music, Soul music"
39,-G0u13COALA,Rainbow in the Dark (2016 Remaster),Provided to YouTube by Rhino/Warner Records\n\...,12118291,139645,PT4M15S,2016-07-23T01:25:57Z,Dio - Topic,None,"Music, Pop music, Rock music"
40,sxDHyYpQNBk,Kingdom (feat. CHNNR),Provided to YouTube by DistroKid\n\nKingdom (f...,718415,9554,PT3M37S,2024-04-04T10:00:56Z,Downstait - Topic,None,"Electronic music, Hip hop music, Music, Rock m..."
41,dRBowc83jVs,Kingdom - Ragile Ragile Lyrical Video | Vijay ...,Watch & Enjoy Ragile Ragile Lyrical Video from...,23363857,226165,PT5M30S,2025-07-29T04:39:06Z,Aditya Music,None,"Film, Music, Music of Asia"
42,4k_2sjvnasE,AVATAR Reacts to Y/N’S,"GN!Y/N — Tamtey (Gender Neutral,Since you can ...",22399,1292,PT11M59S,2026-02-02T20:00:06Z,𝙑𝙚𝙚🍧,None,"Entertainment, Film"
43,3Wn69w0W9C8,Pacas De A Kilo,Provided to YouTube by Universal Music Group\n...,82009148,300556,PT3M34S,2018-06-25T22:15:16Z,Los Tigres Del Norte - Topic,None,"Music, Music of Latin America"
44,8KIYBNbbK4E,What democratic socialism is and how it's diff...,Zohran Mamdani's victory as NYC mayor has put ...,2167,41,PT3M7S,2025-11-16T04:00:07Z,Good Morning America,None,"Politics, Society"
45,P4QAFljGP7s,"""Cold-Blooded Murder"": Families of Trinidadian...",Support our work: https://democracynow.org/don...,157302,4015,PT7M51S,2026-01-30T15:46:01Z,Democracy Now!,None,"Politics, Society"
46,_G6NtIVZhRE,Dio - Heaven And Hell Live In London 2005,Holy Diver DVD,23662641,154674,PT11M17S,2010-10-08T16:39:25Z,DIOCIRCLE,None,"Music, Rock music"
47,cPN4H0sSCHQ,Switch Disco - REACT (feat. Ella Henderson) (L...,"Stream ""REACT"" here: https://switchdisco.lnk.t...",48010016,135738,PT3M22S,2023-01-16T16:58:40Z,SwitchDiscoVEVO,None,"Electronic music, Music, Pop music"
48,YTbRsGRWZW0,The Last in Line (2016 Remaster),Provided to YouTube by Rhino/Warner Records\n\...,10407709,97729,PT5M47S,2016-07-23T01:26:46Z,Dio - Topic,None,"Music, Pop music, Rock music"

Una vez que tenemos el dataframe, lo exportamos en formato csv.

In [ ]:
data_csv = df_data.to_csv("data_videos.csv", index=False)

In [8]:
get_info("T_-XrleDgTI")

,ID,Titulo,Descripcion,Visualizaciones,Numero_likes,Duracion,Fecha_publicacion,Titulo_canal,Subtitulos,Generos
0,T_-XrleDgTI,"""Out for Love"" - Hazbin Hotel (Sing along) Sub...",#hazbinhotel #amazonprimevideo #vivziepop #hel...,3824,71,PT1M27S,2024-02-02T02:04:10Z,Alejo Muñoz,None,"Music, Pop music"

In [ ]:
import Server_PD

In [2]:
import os
print(os.getcwd())

c:\Users\Marina\Documents\Uni\ProyectoDatos\c2526-R1\src\notebooks